# application-qa.yml
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewmqa;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

ewm:
  stats:
    server:
      url: ${SERVICES_STATSSERVER_URI:http://stats-server:9090}