create table if not exists users
(
    id    bigint generated by default as identity,
    name  varchar(255) not null,
    email varchar(255) not null,
    constraint USERS_PK primary key (id),
    constraint unique_email unique (email)
);

create table if not exists categories
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    constraint CATEGORIES_PK primary key (id),
    constraint uq_name unique (name)
);

create table if not exists events
(
    id                 bigint generated by default as identity,
    annotation         varchar(2000)                not null,
    category_id        bigint                      not null,
    created_on         timestamp without time zone,
    description        varchar(7000),
    event_date         timestamp without time zone not null,
    initiator_id       bigint                      not null,
    loc_lat            float                       not null,
    loc_lon            float                       not null,
    paid               bool                        not null,
    participant_limit  int,
    published_on       timestamp without time zone,
    request_moderation bool,
    state              varchar,
    title              varchar(120)                not null,
    constraint EVENTS_PK primary key (id),
    foreign key (category_id) references categories (id),
    foreign key (initiator_id) references users (id),
    constraint enum_state check ( state in ('PENDING', 'PUBLISHED', 'CANCELED') )
);

create table if not exists requests (
    id bigint generated by default as identity,
    created timestamp without time zone not null,
    event_id bigint not null,
    requester_id bigint not null,
    status varchar,
    constraint REQUESTS_PK primary key (id),
    foreign key (event_id) references events(id),
    foreign key (requester_id) references users(id),
    constraint enum_status check (status in ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
);

create table if not exists compilations(
    id bigint generated by default as identity ,
    pinned bool,
    title varchar(50) not null,
    constraint COMPILATIONS_PK primary key (id)
);

create table if not exists compilations_events (
    compilation_id bigint,
    event_id bigint,
    foreign key (compilation_id) references compilations(id),
    foreign key (event_id) references events(id)
);