create table if not exists users
(
    id    bigint generated by default as identity,
    name  varchar(255) not null,
    email varchar(255) not null,
    constraint USERS_PK primary key (id),
    constraint unique_email unique (email)
);

create table if not exists categories
(
    id   bigint generated by default as identity,
    name varchar(255) not null,
    constraint CATEGORIES_PK primary key (id),
    constraint uq_name unique (name)
);

create table if not exists events
(
    id                 bigint generated by default as identity,
    annotation         varchar(500)                not null,
    category_id        bigint                      not null,
    confirmed_requests integer,
    created_on         timestamp without time zone,
    description        varchar,
    event_date         timestamp without time zone not null,
    initiator_id       bigint                      not null,
    loc_lat            float                       not null,
    loc_lon            float                       not null,
    paid               bool                        not null,
    participant_limit  int,
    published_on       timestamp without time zone,
    request_moderation bool,
    state              varchar,
    title              varchar(255)                not null,
    foreign key (category_id) references categories(id)
);