spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always

logging.level.org.springframework:
  orm:
    jpa: INFO
    jpa.JpaTransactionManager: DEBUG
  transaction: INFO
  transaction.interceptor: TRACE

server:
  port: 9090

spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:ewmqa;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
  username: stat
  password:
